config/routes.rb
Rails.application.routes.draw do
  root 'products#search'
  resources :addresses
  resources :drink_types, except: [:show]

  scope 'compras' do
    get 'compra(.:id)', to: 'purchases#show', as: :purchase_show

    get 'cart', to: 'purchases#cart', as: 'cart'
    post 'cart', to: 'purchases#buy'

    post 'buy_product(.:id)', to: 'purchase_products#create', as: :buy
    delete 'buy_product(.:id)', to: 'purchase_products#destroy'
    get 'search(.:type)(.:search)(.:order)', to: 'products#search', as: :search
    post 'update_product(.:id)', to: 'purchase_products#update', as: :update

    get 'buy_cart', to: 'purchases#buy', as: :buy_cart
    get 'ComprasAntigas', to: 'purchases#index', as: :purchases_index
  end

  scope 'user' do
    get 'login', to: 'user_sessions#new', as: :login
    post 'login', to: 'user_sessions#create'

    post 'logout', to: 'user_sessions#destroy', as: :logout

    get 'novo', to: 'users#new', as: :new_user
    post 'novo', to: 'users#create'

    delete '/', to: 'users#destroy'
    get 'perfil(.:id)', to: 'users#show', as: :perfil_user

    get 'money', to: 'users#add_money', as: :money
    post 'money', to: 'users#add_money_logic'
    patch 'perfil(.:id)', to: 'users#update', as: :update_perfil_user

    get 'editar', to: 'users#edit', as: :edit_user
    post 'editar', to: 'users#update'
  end

  resources :products do
    member { patch :favorite }
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true

  has_many :purchases
  has_many :address
  has_one_attached :photo
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: :show

  def new
    @user = User.new
  end

  def edit
    @user = current_user
  end

  def show; end

  def create
    user = User.new(user_args)
    user.money = 0
    begin
      user.save!
      flash[:notice] = 'Usuário criado com sucesso!'
      redirect_to root_path
    rescue => err
      flash[:notice] = err
      redirect_to new_user_path
    end
  end

  def update
    begin
      current_user.update!(user_args)
      image_change(current_user)
      flash[:notice] = 'Usuário editado com sucesso'
      redirect_to perfil_user_path
    rescue => err
      flash[:notice] = err
    end
  end

  def destroy
    user = User.find(params[:id])
    begin
      user.destroy!
      flash[:notice] = 'Usuário deletado com sucesso'
    end
  end

  def add_money
    @user = current_user
  end

  def add_money_logic
    @user = current_user
    begin
      new_money = @user.money.to_f + params[:money].to_f
      @user.update_attributes!(money: new_money)
      flash[:notice] = "Fundos adicionados com sucesso!"
      redirect_to perfil_user_path
    rescue => err
      flash[:warning] = err
    end

  end

  private
  def user_args
    params.require(:user).permit(:name, :password, :email, :password_confirmation, :birthday)
  end

  def not_authenticated
    redirect_to login_path, alert: "Por Favor faça login"
  end

  def image_change(user)
    imagem = params[:user][:photo]
    unless imagem.nil?
      if user.photo.attached?
        user.photo.purge
      end
    user.photo.attach(imagem)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_add_money.html.erb
<%= form_with url: money_path, local:true, method: 'post' do |form| %>

  <div class="field">
    <input type="number" placeholder="Valor (R$)" class="field" <%= form.number_field :money, min: 0, step: 0.01 %>
  </div>

  <div class="actions" style="margin-top: 3px">
    <%= form.submit "Confirmar", id:'add-money-submit' %>
  </div>
  
<% end %>

app/views/users/_form.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <%= stylesheet_link_tag 'login'%>

</head>
<body>
<div class="tudo">



<div class="box">
  <h1>Registrar</h1>
  <%= form_with model: other, local: true, url: another do |user| %>
    <input type="text" placeholder="Nome" class="field" <%= user.text_field :name, required: true %>
    
    <input type="email" placeholder="Email" class="field" <%= user.email_field :email, required: true %>

      <input type="email" placeholder="Email" class="field" <%= user.email_field :email, required: true %>

      <input type="date" placeholder="Data de Nascimento" class="field" <%= user.date_field :birthday, required: true %>

      <input type="password" placeholder="Senha" class="field" <%= user.password_field :password %>

      <input type="password" placeholder="Confirmar senha" class="field"<%= user.password_field :password_confirmation %>

      <%= user.submit "Cadastrar" %>
  <% end %>
  </div>

  <style>
  .site-footer{
    display: none;
  }
  .tudo{
    margin-top: -4.5%
  }
  </style>
</div>
</body>
</html>

app/views/users/edit.html.erb
<%= stylesheet_link_tag 'login' %>
<div class="tudo">
    <body>
    <div class="box">
      <h1>Editar</h1>
      <%= form_with model: @user, url: edit_user_path, method: :post, local: true do |user| %>
        <input type="text" placeholder="Nome" class="field" <%= user.text_field :name, required: true, value: @user.name %>

        <input type="date" placeholder="Data de Nascimento" class="field" <%= user.date_field :birthday, required: true, value: @user.birthday %>

        <input type="email" placeholder="Email" class="field" <%= user.email_field :email, required: true %>
        
        <%= user.submit "Editar" %>
      <% end %>
    </div>
  </body>
</div>

app/views/users/new.html.erb
<%= render 'form', other: @user, another: new_user_path %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <%= stylesheet_link_tag 'perfil'%>

</head>
<body>
<div class="tudo">

  <div class="box">
    <%= form_with model: current_user, url: :update_perfil_user, method: :patch do |form| %>

  <div class="personal-image">
      <label class="label">
        <%= form.file_field :photo %>
        <figure class="personal-figure">
        <%if @current_user.photo.attached? %>
          <%= image_tag @current_user.photo, :class => "personal-avatar", :atl => "Avatar" %>
        <% else %>
          <img class="personal-avatar", alt="Avatar" src="https://elaele.com.br/img/anonimo.png">
        <% end %>
        <figcaption class="personal-figcaption">
          <img src="https://raw.githubusercontent.com/ThiagoLuizNunes/angular-boilerplate/master/src/assets/imgs/camera-white.png">
          <div class="actions">
            <%= form.submit "Enviar" %>
          </div>
        <% end %>
          </figcaption>
        </figure>
      </label>
    </div>

    <div style="padding-top: 5px;">
      <p>
        <strong>Nome:</strong><br>
        <%= current_user.name %>
      </p>

      <p >
        <strong>E-mail:</strong><br>
        <%= current_user.email %>
      </p>

      <p >
        <strong>Dinheiro:</strong><br>
        <%= number_to_reais(current_user.money) %><br>
        <button type="button" id="add-funds-btn" data-toggle="collapse" data-target="#funds-form" >Adicionar Fundos</button>
        <div id="funds-form" class="collapse"><%= render 'add_money' %></div>
      </p>
      <strong>Endereços:</strong><br>
      <table>
        <thead>
          <div class="row col">
            <div class="col-3">CEP</div>
            <div class="col-5">Endereço</div>
            <div class="col-2"></div>
            <div class="col-2"></div>
          </div>
        </thead>

        <tbody>
          <% current_user.address.each do |address| %>
            <% if address.visible == true%>
              <div class= "row col">
                <div class="col-3"><%= address.cep %></div>
                <div class="col-5"><%= address.address %></div>
                <div class="col-2"> <%= link_to 'Editar', edit_address_path(address) %> </div>
                <div class="col-2"> <%= link_to 'Deletar', address_path(address), method: :delete, data: { confirm: 'Você tem certeza?' } %> </div>
              </div>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <%= link_to 'Adicionar Endereço', new_address_path %> <br>
  <div style="padding-top: 40px; display:flex; justify-content: space-between"class="row">
    <% if current_user.admin %>
      <%= link_to "Ver Produtos", products_path  %>
      <br>
      <%= link_to "Ver Tipos de Bebida", drink_types_path  %>
    <% else %>
      <%= link_to "Seu Carrinho", cart_path %>
      <br>
      <%= link_to 'Compras já realizadas', purchases_index_path %>
        <br>
      <%= link_to 'Editar Usuário', edit_user_path %>
    <% end %>
  </div>
  </div>
  <style>
  .site-footer{
    display: none;
  }
  </style>
</div>
</body>
</html>