config/routes.rb
Rails.application.routes.draw do
  root 'products#search'
  resources :addresses
  resources :drink_types, except: [:show]

  scope 'compras' do
    get 'compra(.:id)', to: 'purchases#show', as: :purchase_show

    get 'cart', to: 'purchases#cart', as: 'cart'
    post 'cart', to: 'purchases#buy'

    post 'buy_product(.:id)', to: 'purchase_products#create', as: :buy
    delete 'buy_product(.:id)', to: 'purchase_products#destroy'
    get 'search(.:type)(.:search)(.:order)', to: 'products#search', as: :search
    post 'update_product(.:id)', to: 'purchase_products#update', as: :update

    get 'buy_cart', to: 'purchases#buy', as: :buy_cart
    get 'ComprasAntigas', to: 'purchases#index', as: :purchases_index
  end

  scope 'user' do
    get 'login', to: 'user_sessions#new', as: :login
    post 'login', to: 'user_sessions#create'

    post 'logout', to: 'user_sessions#destroy', as: :logout

    get 'novo', to: 'users#new', as: :new_user
    post 'novo', to: 'users#create'

    delete '/', to: 'users#destroy'
    get 'perfil(.:id)', to: 'users#show', as: :perfil_user

    get 'money', to: 'users#add_money', as: :money
    post 'money', to: 'users#add_money_logic'
    patch 'perfil(.:id)', to: 'users#update', as: :update_perfil_user

    get 'editar', to: 'users#edit', as: :edit_user
    post 'editar', to: 'users#update'
  end

  resources :products do
    member { patch :favorite }
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :require_login
  before_action :check_funds, only: :buy
  before_action :check_stock, only: :buy
  before_action :check_address_exist, only: :buy

  def show
    @purchase = Purchase.find(params[:id])
  end

  def cart
    @cart = current_user.purchases.find_by(bought: false)
    @user_addresses = current_user.address.where(visible: true)
  end

  def buy
    @cart = current_user.purchases.find_by(bought: false)
    price = @cart.price
    pay_up(price)
    change_stock(@cart, true)
    begin
      @cart.update!(bought: true, address_id: params[:address_id])
      flash[:notice] = 'Compra realizada com sucesso!'
      create_cart
      redirect_to root_path
    rescue => err
      print err
      change_stock(cart, false)
      flash[:warning] = 'Algo deu errado!'
      redirect_to cart_path
    end
  end

  def index
    @purchases = current_user.purchases.where('bought = true')
  end

  private
  def check_funds
    cart = current_user.purchases.find_by(bought: false)
    money = current_user.money
    if money < cart.price
      flash[:warning] = 'Você não tem dinheiro suficiente para realizar essa compra.'
      redirect_to perfil_user_path
    end
  end

  def pay_up (price)
    user = current_user
    result = user.money - price
    begin
      user.update!(money: result)
    rescue => err
      print err
    end
  end

  def check_stock
    flash[:notice] = ''
    cart = current_user.purchases.find_by(bought: false)
    control = false
    cart.purchase_products.each do |associative|
      available = associative.product.quantity
      requested = associative.quantity
      if requested > available
        flash[:warning] << "Não pussuimos #{associative.product.name} o suficiente para atender seu pedido \n"
        control = true
      end
    end
    if control
      redirect_to cart_path
    end
  end

  def change_stock (cart, bool)
    if bool
      cart.purchase_products.each do |associative|
        product = associative.product
        new_quantity = product.quantity - associative.quantity
        begin
          product.update!(quantity: new_quantity)
        rescue => err
          print err
        end
      end
    else
      cart.purchase_products.each do |associative|
        product = associative.product
        new_quantity = product.quantity + associative.quantity
        begin
          product.update!(quantity: new_quantity)
        rescue => err
          print err
        end
      end
    end
  end

  # Método para verificar se o usuário tem um endereço cadastrado antes de efetuar uma compra.
  def check_address_exist
    if Address.find_by(user_id: current_user.id, visible: true) == nil
      flash[:warning] = "Cadastre um endereço antes de concluir a compra!"
      redirect_to perfil_user_path
    end
  end

end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/cart.html.erb
<body>
  <%= stylesheet_link_tag 'cart' %>
  <div clas="tudo">
  <% if not @cart.products == [] %>
    <div class='container boxNot'>
      <h1>Seu carrinho:</h1>
        <div class="row col-14">
          <div class="col-2">Foto</div>
          <div class="col">Nome</div>
          <div class="col-2">Quantidade</div>
          <div class="col-2">Estoque</div>
          <div class="col-2">Custo</div>
          <div class="col">Alterar quantidade</div>
          <div class="col"></div>
        </div>
      <% @cart.purchase_products.each do |product| %>
        <tr>
          <div class="row media">
            <div class="col-2 foto">
                <%= image_tag product.product.photo, width: '100px', height: '130px'%>
            </div>

            <div class="row media-body">
            
            <div class="col">
              <h5 class="mt-0"><%= product.product.name.capitalize %></h5>
            </div>

            <div class="col">

              <% if product.product.quantity.to_i < product.quantity.to_i %>
                <div style="color: red">
                  <%= product.quantity.to_i %>
                </div>
              <% else %>
                <div>
                  <%= product.quantity.to_i %>
                </div>
              <% end %>

            </div>

            <div class="col">

              <%= product.product.quantity.to_i %><br>
            
            </div>


            <div class="col">
                R$<%= product.product.value * product.quantity.to_i %><br>
            </div>

            <%= form_with url: update_path(product.id), local:  true do |update| %>

              <div class="col">
                  <div class="field">
                    <%= update.number_field :quantity, in: 1..(product.product.quantity), class: "alterando" %>
                  </div>

                  <div class="actions">
                    <%= update.submit 'Alterar' %>
                  </div>
              </div>

            <% end %>


            <div class="col">
              <%= link_to 'Remover', buy_path(product.id), method: :delete %>
            </div>
              </div>
            </div>
        </tr>
      <% end %>
      </tbody>
      </table>
      <h4>Total: <%= number_to_reais(@cart.price) %></h4>

      <%= form_with url: cart_path, method: 'post' do |form| %>

        <div class="field">
          <%= form.label :address_id, 'Endereços' %>
          <%= form.collection_select(:address_id, @user_addresses, :id, :address) %>
        </div>

        <div class="actions">
          <%= form.submit "Finalizar essa compra" %>
        </div>
      <% end %>
    </div>
</div>

  <% else %>
    <div class='boxYes'>
    <h3>Seu carrinho está vazio! Veja nossos produtos <%= link_to 'aqui', root_path %></h3>
    </div>
  <% end %>
  </div>
</body>

app/views/purchases/index.html.erb
<body>
  <%= stylesheet_link_tag 'cart' %>
  <div clas="tudo">
    <div class='container boxNot'>
      <h1 style="padding-bottom: 50px;">Compras Antigas:</h1>
        <div class="row categorias">
          <div class="col">Quantidade de produtos</div>
          <div class="col">Preço</div>
          <div class="col-4">Endereço de envio</div>
          <div class="col">Comprado em</div>
          <div class="col"></div>
        </div>
      <% @purchases.each do |purchase| %>
          <div class="row col-14">
            <div class="col">
              <%= purchase.products.length %>
            </div>
            <div class="col">
              R$<%= purchase.price.round(2) %>
            </div>

            <div class="col-4">
              <%= Address.find(purchase.address_id).address %>
            </div>

            <div class="col">
              <%= purchase.updated_at %>
            </div>
            <div class="col details">
              <%= link_to 'Detalhes', purchase_show_path(purchase.id) %>
            </div>
          </div>
      <% end %>
    </div>
</div>
</body>

<style>
.boxNot{
  margin-top: 5%;
  background-color: darkslategray;
}
</style>

app/views/purchases/show.html.erb
<% if not @purchase.products == [] %>
<body>
  <%= stylesheet_link_tag 'cart' %>
  <div clas="tudo">
    <div class='container boxNot'>
      <h1>Seu carrinho:</h1>
        <div class="row categorias">
          <div class="col">Foto</div>
          <div class="col">Nome</div>
          <div class="col">Quantidade</div>
          <div class="col">Custo</div>
        </div>
      <% @purchase.purchase_products.each do |product| %>
        <tr>
          <div class="row media">
            <div class="col-3 foto">
                <%= image_tag product.product.photo, width: '100px', height: '130px'%>
            </div>

            <div class="row media-body">
            
            <div class="col">
              <h5 class="mt-0"><%= product.product.name.capitalize %></h5>
            </div>

            <div class="col">

              <% if product.product.quantity.to_i < product.quantity.to_i %>
                <div style="color: red">
                  <%= product.quantity.to_i %>
                </div>
              <% else %>
                <div>
                  <%= product.quantity.to_i %>
                </div>
              <% end %>

            </div>

            <div class="col">
                R$<%= product.product.value * product.quantity.to_i %><br>
            </div>

              </div>
            </div>
        </tr>
      <% end %>
      </tbody>
      </table>
      <h4>Total: <%= number_to_reais(@purchase.price) %></h4>

      <%= form_with url: cart_path, method: 'post' do |form| %>

  <%= link_to 'Voltar', purchases_index_path %>
      <% end %>
    </div>
</div>
<% else %>
  <h3>Você ainda não realizou uma compra! Comece agora clicando <%= link_to 'aqui', root_path %></h3>
<% end %>
  </div>

</body>