config/routes.rb
Rails.application.routes.draw do
  root 'products#search'
  resources :addresses
  resources :drink_types, except: [:show]

  scope 'compras' do
    get 'compra(.:id)', to: 'purchases#show', as: :purchase_show

    get 'cart', to: 'purchases#cart', as: 'cart'
    post 'cart', to: 'purchases#buy'

    post 'buy_product(.:id)', to: 'purchase_products#create', as: :buy
    delete 'buy_product(.:id)', to: 'purchase_products#destroy'
    get 'search(.:type)(.:search)(.:order)', to: 'products#search', as: :search
    post 'update_product(.:id)', to: 'purchase_products#update', as: :update

    get 'buy_cart', to: 'purchases#buy', as: :buy_cart
    get 'ComprasAntigas', to: 'purchases#index', as: :purchases_index
  end

  scope 'user' do
    get 'login', to: 'user_sessions#new', as: :login
    post 'login', to: 'user_sessions#create'

    post 'logout', to: 'user_sessions#destroy', as: :logout

    get 'novo', to: 'users#new', as: :new_user
    post 'novo', to: 'users#create'

    delete '/', to: 'users#destroy'
    get 'perfil(.:id)', to: 'users#show', as: :perfil_user

    get 'money', to: 'users#add_money', as: :money
    post 'money', to: 'users#add_money_logic'
    patch 'perfil(.:id)', to: 'users#update', as: :update_perfil_user

    get 'editar', to: 'users#edit', as: :edit_user
    post 'editar', to: 'users#update'
  end

  resources :products do
    member { patch :favorite }
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :drink_type
  validates :name, presence: true
  validates :value, presence: true
  validates :quantity, presence: true
  validates :volume, presence: true
  has_one_attached :photo
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    before_action :authorize_admin, except: [:show, :search]

    def search
        @drink_types = DrinkType.all

        # Pegar todos os produtos sem ordem ou filtro
        @filtered_products = Product.all

        # Pegar os favoritos
        @faves = Product.where('favorite = true')

        # Filtrando por nome na busca se necessário
        if params[:search] != nil
            @filtered_products = Product.search(params[:search].downcase)
        end
        
        # Ordenação
        if params[:order] != '0'
            # Ordenar A-Z
            if params[:order] == '1'
                @filtered_products = @filtered_products.order(name: :asc)

            # Ordenar Z-A
            elsif params[:order] == '2'
                @filtered_products = @filtered_products.order(name: :desc)

            # Ordenar por preço crescente
            elsif params[:order] == '3'
                @filtered_products = @filtered_products.order(value: :asc)

            # Ordenar por preço decrescente
            elsif params[:order] == '4'
                @filtered_products = @filtered_products.order(value: :desc)

            # Ordenar por tipo de produto
            elsif params[:order] == '5'
                @filtered_products = @filtered_products.order(:drink_type_id)
            end
        end

        # Filtrando por preço se necessário
        if params[:price] != '0' && params[:price] != nil

            # Extraindo os limites do filtro de preço se selecionado
            min, max = params[:price].split('-')

            # Um valor máximo não foi informado
            if(max == "MAX")
                @filtered_products = @filtered_products.where("value > ?", min.to_i )
            else
                @filtered_products = @filtered_products.where(value: min.to_i..max.to_i)
            end
        end

        # Filtrando por tipo de bebida se necessário
        if params[:type] != nil && params[:type] != '0'
            @filtered_products = @filtered_products.where(:drink_type_id => params[:type])
        end

        # Retirando os produtos que não estão visiveis/foram excluidos
        @filtered_products = @filtered_products.where(visible: true)

        # Atualizando Pagy
        @pagy, @records = pagy(@filtered_products)

        render 'search'
    end

    def index
        @products = Product.where(visible: true)
    end


    def new
        @product = Product.new
        @drink_types = DrinkType.all
        @page_title = "Cadastrar Produto"
    end

    def create
        product = Product.new(products_params)
        product.visible = true
        begin
            product.save!
            flash[:notice] = "Produto #{product.name} criado com sucesso!"
            redirect_to product_path(product)
        rescue => err
            flash[:warning] = err
            redirect_to new_product_path
        end
    end

    def edit
        @product = Product.find(params[:id])
        @drink_types = DrinkType.all
        @page_title = "Editar Produto"
    end

    def update
        product = Product.find(params[:id])
        begin
            product.update!(products_params)
            flash[:notice] = "Produto #{product.name} modificado com sucesso!"
            redirect_to product_path(product)
        rescue => err
            flash[:warning] = err
            redirect_to edit_product_path
        end
    end

    def show
        @product = Product.find(params[:id])
    end

    def destroy
        product = Product.find(params[:id])
        begin
            product.update!(visible: false)
            flash[:notice] = "Produto #{product.name} apagado com sucesso!"
        rescue => err
            flash[:warning] = err
        ensure
            redirect_to products_path
        end
    end

    def favorite
        product = Product.find(params[:id])
        begin
            product.update_attributes!(favorite: !product.favorite)
        rescue => err
            flash[:warning] = err
        ensure
            redirect_to products_path
        end
    end

    private

    def products_params
        unless params['product'][:name].nil?
            params['product'][:name] = params['product'][:name].downcase
        end
        return params.require('product').permit(:name, :value, :volume, :quantity, :favorite, :drink_type_id, :description, :photo)
    end

end

app/helpers/products_helper.rb
module ProductsHelper

    def stock_information(stock)
        if stock > 25
            return '<p class="in-stock">Em estoque</p>'.html_safe
        elsif stock > 0
            return ('<p class="low-stock">Apenas ' + stock.to_s + ' itens restantes</p>').html_safe
        else
            return '<p class="no-stock">Produto indisponível<p>'.html_safe
        end
    end

end

app/views/products/_form.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <%= stylesheet_link_tag 'product_form'%>

</head>
<body>

<div class="box">
  <h1><%= @page_title %></h1>
  <%= form_with model: @product, local: true do |form| %>
      <input type="text" placeholder="Nome" class="field" <%= form.text_field :name, required: true %>

      <input type="number" placeholder="Valor (R$)" class="field" <%= form.number_field :value, min: 0, step: 0.01, required: true %>

      <input type="number" placeholder="Volume (ml)" class="field" <%= form.number_field :volume, min: 0, step: 1, required: true %>

      <input type="number" placeholder="Quantidade" class="field" <%= form.number_field :quantity, min: 0, step: 1, required: true %>

      <%= form.collection_select :drink_type_id, @drink_types, :id, :name, {:include_blank => "Tipo de Bebida"}, required: true %>

      <textarea type="text_area" placeholder="Descrição do Produto" class="field" <input type="text" placeholder="Nome" class="field" <%= form.text_area :description %>
      
      <!-- Label acts as a button to file input, while it stays hidden on page -->
      <label id="file-label" for="file-select">Selecionar Imagem</label>
      <input id="file-select" type="file" placeholder="Imagem" class="field" <%= form.file_field :photo %>
    
      <%= form.submit "Confirmar" %>
  <% end %>
</div>

<script>
  $( document ).on('turbolinks:load',function(){
    var filepath = document.getElementById('file-select');
    var filelabel = document.getElementById('file-label');
    
    filepath.addEventListener('change', function(){
      var filename = (this.value).split(/(\\|\/)/g).pop()
      filelabel.innerHTML = filename;
    })
  });
</script>

</body>
</html>

app/views/products/_show_admin.html.erb
<div class="container">

  <div class="row">
    <p>
      <%= link_to 'Todos os Produtos', products_path %>
      <i class="fa fa-angle-right fa-1x"></i>
      <%= link_to @product.drink_type.name, search_path(@product.drink_type.id) %>
    </p>
  </div>

  <div class="row justify-content-center">
    <div class="col-md-4">
      <% if @product.photo.attached? %>
        <%= image_tag @product.photo, :class => 'product-image img-fluid' %>
      <% else %>
        <%= image_tag asset_path('image-not-found.png'), :class => 'product-image img-fluid' %>
      <% end %>
    </div>

    <div class="col-md-6">
      <div class="container-fluid product-name">
        <p><%= @product.name.capitalize %></p>
      </div>
      <div class="container-fluid product-volume">
        <p><%= "#{@product.volume} mL" %></p>
      </div>
      <div class="container-fluid product-price">
        <h3><%= number_to_reais(@product.value) %></h3>
      </div>
      <div class="container-fluid product-stock">
        <p><strong>Quantidade Disponível:</strong> <%= @product.quantity %></p>
      </div>
      <div class="container-fluid change-stock" id="change-stock">
        <button class="change-stock-button'">Mudar o estoque</button>
      </div>
      <div class="container-fluid product-favorite">
        <p><strong>Favorito: </strong><%= human_boolean(@product.favorite) %></p>
      </div>

      <div class="container-fluid">
         <% if  @product.drink_type.alcoholic == true %>
          <p>
            <strong style="color: red;"> ATENÇÃO! </strong><br>
            Esta bebida não é recomendada para menores de 18 anos. <br> Contém Álcool.
          </p>
        <% end %>
      </div>

      <div class="container-fluid">
        <%= link_to 'Editar', edit_product_path(@product), :class => "btn btn-primary" %>
      </div>
      <div class="container-fluid">
        <%= link_to 'Deletar', product_path(@product), :class => "btn btn-danger mt-2", method: :delete, data: { confirm: 'Você tem certeza?' } %>
      </div>
    </div>
  </div>
  
  <div class="product-description">
    <h4 id="description-title">Descrição da Bebida</h4>
    <p id="description"><%= @product.description%></p>
  </div>
</div>

<td></td>

<script>
  let div = document.getElementById('change-stock')
  function changeStock() {
      div.innerHTML = '<%= form_with model: @product, local: true do |update| %>' +
          '<%= update.label :quantity, 'Quantidade' %>' +
          '<%= update.number_field :quantity, value: @product.quantity %>' +
          '<%= update.submit %>' +
          '<% end %>'
      div.removeEventListener('click', changeStock)
  }
  div.addEventListener("click", changeStock)
</script>

app/views/products/_show_user.html.erb
<div class="container">

  <div class="row">
    <p>
      <%= link_to 'Todos os Produtos', root_path %>
      <i class="fa fa-angle-right fa-1x"></i>
      <%= link_to @product.drink_type.name, search_path(@product.drink_type.id) %>
    </p>
  </div>

  <div class="row justify-content-center">
    <div class="col-md-4">
      <% if @product.photo.attached? %>
        <%= image_tag @product.photo, :class => 'product-image img-fluid' %>
      <% else %>
        <%= image_tag asset_path('image-not-found.png'), :class => 'product-image img-fluid' %>
      <% end %>
    </div>

    <div class="col-md-6">
      <div class="container-fluid product-name">
        <p><%= @product.name.capitalize %></p>
      </div>
      <div class="container-fluid product-volume">
        <p><%= "#{@product.volume} mL" %></p>
      </div>
      <div class="container-fluid product-price">
        <h3><%= number_to_reais(@product.value) %></h3>
      </div>
      <div class="container-fluid pb-0 product-stock">
        <%= stock_information(@product.quantity) %>
      </div>
      <div class="container-fluid">
         <% if  @product.drink_type.alcoholic == true %>
          <p>
            <strong style="color: red;"> ATENÇÃO! </strong><br>
            Esta bebida não é recomendada para menores de 18 anos. <br> Contém Álcool.
          </p>
        <% end %>
      </div>
      <br>
      <div class="container-fluid product-purchase">
        <%= form_with url: buy_path(@product.id), local: true do |buy| %>
          <div class="field">
            <%= buy.label :quantity, 'Quantidade:' %>
            <%= buy.number_field :quantity, in: 0..(@product.quantity) %>
          </div>

          <div class="actions">
            <%= buy.submit 'Adicionar ao Carrinho', :disabled => !@product.quantity?, class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class="product-description">
    <h4 id="description-title">Descrição da Bebida</h4>
    <p id="description"><%= @product.description%></p>
  </div>
</div>

app/views/products/edit.html.erb
<%= render 'form', address: @address %>

app/views/products/index.html.erb
<%= stylesheet_link_tag 'drink_types' %>


<div class="text-center">
<h1>Produtos Disponíveis</h1>
<h5 class="justify-content-left"><%= link_to 'Novo Produto', new_product_path %></h5>
</div>

<table>
  <thead>
  <tr>
    <th scope="col">Nome</th>
    <th scope="col">Valor</th>
    <th scope="col">Volume (mL)</th>
    <th scope="col">Tipo</th>
    <th scope="col">Quantidade</th>
    <th scope="col">Favorito</th>
    <th scope="col" colspan="9"> Ações</th>
  </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name.capitalize %></td>
      <td><%= number_to_reais(product.value) %></td>
      <td><%= product.volume %></td>
      <td><%= product.drink_type.name %></td>
      <td><%= product.quantity %></td>
      <td><%= human_boolean(product.favorite) %></td>
      <td>
        <%= link_to product_path(product) do %>
          <i class="action-button fa fa-file-text"></i>
        <% end %>
        <% if product.favorite %>
          <%= link_to favorite_product_path(product), :method => :patch do %>
            <i class="action-button fa fa-heart" style="color: red"></i>
          <% end %>
      <% else %>
          <%= link_to favorite_product_path(product), :method => :patch do %>
            <i class="action-button fa fa-heart-o" style="color: red"></i>
          <% end %>
      <% end %>
      <%= link_to edit_product_path(product) do %>
      <i class="action-button fa fa-pencil-square-o"></i>
      <% end %>
        <%= link_to product_path(product), method: :delete, data: { confirm: 'Você tem certeza?' } do%>
          <i class="action-button fa fa-trash"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<style>
  .fa-heart:hover, .fa-heart-o:hover{
    background-color: white;
  }
</style>

app/views/products/search.html.erb
<head>
  <%= stylesheet_link_tag 'card' %>
  <%= stylesheet_link_tag 'search' %>
  <%= javascript_include_tag 'search'%>
  <%= javascript_include_tag 'carousel' %>
</head>
<!doctype html>
  <html lang="en">

  <body>
    
<h2 style="display: flex; justify-content:center; color: red; padding: 4% 0%;">Principais Produtos</h2>

<div class="owl-carousel owl-theme">
    <% @faves.each do |product| %>

  <section id="produtos" class="produtos-section">
  <div class="produtos-grid">
  <div class="product">
    <div class="imgbox">
      <% if product.photo.attached? %>
        <%= image_tag product.photo, top: '30px', width: '90%', height: '80%'%>
      <% else %>
        <%= image_tag asset_path('image-not-found.png'), top: '30px', width: '90%', height: '80%'%>
      <% end %>
    </div>
    <div class="specifice">
      <h2><%= product.name.capitalize %></h2>
      <div class="price"><%= number_to_reais(product.value) %></div>
      <a href="<%= product_path(product.id) %>">Saiba mais</a>
    </div>
</div>

    
  </div>
</section>
  <% end %>

</div>



<!-- START PROJECTS SECTION -->

<section id="produtos" class="produtos-section">
  <div class="produtos-grid">
  <% @records.each do |product| %>
  <div class="product">
    <div class="imgbox">
      <% if product.photo.attached? %>
        <%= image_tag product.photo, top: '30px', width: '90%', height: '80%'%>
      <% else %>
        <%= image_tag asset_path('image-not-found.png'), top: '30px', width: '90%', height: '80%'%>
      <% end %>
    </div>
    <div class="specifice">
      <h2><%= product.name.capitalize %></h2>
      <div class="price"><%= number_to_reais(product.value) %></div>
      <a href="<%= product_path(product.id) %>">Saiba mais</a>
    </div>
</div>

  <% end %>
    
  </div>
</section>

<!-- END PROJECTS SECTION -->

  <div style="display: flex; justify-content: center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
  </body>
</html>

app/views/products/show.html.erb
<%= stylesheet_link_tag 'products' %>

<% if is_admin? == true %>
  <%= render 'show_admin' %>
<% else %>
  <%= render 'show_user' %>
<% end %>