config/routes.rb
Rails.application.routes.draw do
  root 'products#search'
  resources :addresses
  resources :drink_types, except: [:show]

  scope 'compras' do
    get 'compra(.:id)', to: 'purchases#show', as: :purchase_show

    get 'cart', to: 'purchases#cart', as: 'cart'
    post 'cart', to: 'purchases#buy'

    post 'buy_product(.:id)', to: 'purchase_products#create', as: :buy
    delete 'buy_product(.:id)', to: 'purchase_products#destroy'
    get 'search(.:type)(.:search)(.:order)', to: 'products#search', as: :search
    post 'update_product(.:id)', to: 'purchase_products#update', as: :update

    get 'buy_cart', to: 'purchases#buy', as: :buy_cart
    get 'ComprasAntigas', to: 'purchases#index', as: :purchases_index
  end

  scope 'user' do
    get 'login', to: 'user_sessions#new', as: :login
    post 'login', to: 'user_sessions#create'

    post 'logout', to: 'user_sessions#destroy', as: :logout

    get 'novo', to: 'users#new', as: :new_user
    post 'novo', to: 'users#create'

    delete '/', to: 'users#destroy'
    get 'perfil(.:id)', to: 'users#show', as: :perfil_user

    get 'money', to: 'users#add_money', as: :money
    post 'money', to: 'users#add_money_logic'
    patch 'perfil(.:id)', to: 'users#update', as: :update_perfil_user

    get 'editar', to: 'users#edit', as: :edit_user
    post 'editar', to: 'users#update'
  end

  resources :products do
    member { patch :favorite }
  end
end

app/views/layouts/application.html.erb
<head>
    <title>RessacaTrainee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'navbar'%>
    <%= stylesheet_link_tag 'footer'%>
    <%= stylesheet_link_tag 'search' %>
    <%= javascript_include_tag 'search'%>

    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">

  </head>
<!DOCTYPE html>
<html>
  

<body>

<div id="popup" class="popup modal">
  <div class="textoPopup">
    <%= form_with url: search_url, method: 'get', local: true do |search| %>
      <%= search.text_field :search, class: 'search-box' %><br>
      <div class="search-select">
        <%= search.select :price, options_for_select([['Faixa de preço', '0'],
                                                    ['Menos de 25 reais','0-25'],
                                                    ['Entre 25 e 50 reais','25-50'],
                                                    ['Entre 50 e 100 reais','50-100'],
                                                    ['Mais de 100 reais','100-MAX']]) %>

        <%= search.select :type, options_for_select((@drink_types_search.collect { |drink_type| [drink_type.name, drink_type.id] }) << ['Tipo de Bebida', '0'], 0) %>
        
        <%= search.select :order, options_for_select([['Ordenar Por', '0'],
                                                    ['A-Z','1'],
                                                    ['Z-A','2'],
                                                    ['Preço Crescente','3'],
                                                    ['Preço Decrescente','4'],
                                                    ['Tipo de Produto','5']]) %>
      </div>
      
      <%= search.submit 'Pesquisar', class:'pesquisar'%> 
      <h3><a style="color: red; padding-left: 90%;" href="javascript: fechar();"><%= fa_icon "close", class: "fa" %></a></h3></li>
    <% end %>
  </div>
</div>

<div class="geral">
  <div class="nav">
    <div class="logo">
      <a href="<%= root_path %>"><h5 class="espaço"> {Ressaca Trainee} </h5></a>
    </div>
    <ul class="nav-links">
      <li><a href="javascript: abrir();"> <i class="fa fa-2x fa-search"></i></a></li>
      <li><a href="<%= root_path %>"><i class="fa fa-home fa-2x"></i></a></li>
        <% if current_user %>
          <li><a href="<%= perfil_user_path%>"><i class="fa fa-2x fa-user"></i></a></li>
          <li><%= link_to '<i class="fa fa-2x fa-sign-out"></i>'.html_safe,logout_path, method: :post %></li>
          <li><a href="<%= cart_path %>"><i class="fa fa-shopping-cart fa-2x"></i></a></li>
        <% else %>
          <li><a href="<%= new_user_path %>"><i class="fa fa-2x fa-user-plus"></i></a></li>
          <li><a href="<%= '/user/login' %>"><i class="fa fa-2x fa-sign-in"></i></a></li>
        <% end %>
    </ul>
    </div>


    <!-- Pop-up -->
    <div class="modal fade" id="Pop-up" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <% flash.each do |type, msg| %>
              <% if type == 'notice' %>
                <div style="color: green">
                  <%= msg %>
                </div>
              <% elsif type == 'warning'%>
                <div style="color: red">
                  <%= msg %>
                </div>
              <% end %>

            <% end %>


          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

     <!--Renderiza o pop-up quando chega um notice-->
    <% flash.each do |type, msg| %>
      <%= javascript_tag "ShowPopup()" %>
    <% end %>

    <%= yield %>
    </div>

      <!-- Site footer -->
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-9 col-md-5">
            <h6>Desenvolvido por:</h6>
            <p class="text-justify">André Macedo<br>Arthur Mota<br>Felipe Lima<br>Fernando Jorge</p>
          </div>

          <div class="col-xs-6 col-md-5">
            <h6>Linguagens:</h6>
            <ul class="footer-links">
              <li><a href="#">Ruby</a></li>
              <li><a href="#">Javascript</a></li>
              <li><a href="#">HTML</a></li>
              <li><a href="#">CSS</a></li>
            </ul>
          </div>

          <div class="col-xs-6">
            <h6>Links:</h6>
            <ul class="footer-links">
              <li><a href="https://github.com/Nandosts/Ressaca-trainee">Repositório Github</a></li>
              <li><a href="http://www.struct.unb.br/">Empresa Júnior</a></li>
            </ul>
          </div>
        </div>
      </div>
</footer>
  </body>
</html>